### ISSUE TITLE
Clarify the Mono situation

### ISSUE THREAD

**Issue by tpetricek** [FHash/FHashPresentation#1]
I started looking at the presentation - on the second slide, I see lots of useful information, the second slide does not provide clear answer to the question - **Does it work on Mono?**

Given the importance of the "Mono situation" for FHash, I think we should answer this question on the second slide - to make sure readers do not close the presentation before learning about this important point.

I think we should swap slide #2 and #3!

**Comment by Krzysztof-Cieslak** [comment]
Done!
