### ISSUE TITLE
Can we hide disclaimer somewhere?

### ISSUE THREAD

**Issue by tpetricek** [FHash/FHashPresentation#2]
The FSharp Software Foundation has a very strong department full of secret agents that go after everyone who uses their logo in incorrect ways (or says anything that they don't like). To make sure we do not get killed (or whatever), it might be good idea to put a little disclaimer somewhere:

> The FHash software foundation is in *no* way affiliated to the F# Software Foundation and any statements made here are not official statements of the F# Software Foundation or any of its members (especially not Tomas). Any similarities are purely incidental, aside from the fact that F# also works on Mono.

As I'm on the F# Foundation board, I would probably be the first to get killed. Thanks :-)

**Comment by Krzysztof-Cieslak** [comment]
Well, does it mean I am in danger because of my avatar? ;)

As for now I've added additional slide on the end of presentation  -https://github.com/FHash/FHashPresentation/commit/03f8352e011cfe17423d0d3335761b92216676c9
